INSERT INTO states(state_name) VALUES ("Alabama");
INSERT INTO states(state_name) VALUES ("Alaska");
INSERT INTO states(state_name) VALUES ("Arizona");
INSERT INTO states(state_name) VALUES ("Arkansas");
INSERT INTO states(state_name) VALUES ("California");
INSERT INTO states(state_name) VALUES ("Colorado");
INSERT INTO states(state_name) VALUES ("Connecticut");
INSERT INTO states(state_name) VALUES ("Delaware");
INSERT INTO states(state_name) VALUES ("Florida");
INSERT INTO states(state_name) VALUES ("Georgia");
INSERT INTO states(state_name) VALUES ("Hawaii");
INSERT INTO states(state_name) VALUES ("Idaho");
INSERT INTO states(state_name) VALUES ("Illinois");
INSERT INTO states(state_name) VALUES ("Indiana");
INSERT INTO states(state_name) VALUES ("Iowa");
INSERT INTO states(state_name) VALUES ("Kansas");
INSERT INTO states(state_name) VALUES ("Kentucky");
INSERT INTO states(state_name) VALUES ("Louisiana");
INSERT INTO states(state_name) VALUES ("Maine");
INSERT INTO states(state_name) VALUES ("Maryland");
INSERT INTO states(state_name) VALUES ("Massachusetts");
INSERT INTO states(state_name) VALUES ("Michigan");
INSERT INTO states(state_name) VALUES ("Minnesota");
INSERT INTO states(state_name) VALUES ("Mississippi");
INSERT INTO states(state_name) VALUES ("Missouri");
INSERT INTO states(state_name) VALUES ("Montana");
INSERT INTO states(state_name) VALUES ("Nebraska");
INSERT INTO states(state_name) VALUES ("Nevada");
INSERT INTO states(state_name) VALUES ("New Hampshire");
INSERT INTO states(state_name) VALUES ("New Jersey");
INSERT INTO states(state_name) VALUES ("New Mexico");
INSERT INTO states(state_name) VALUES ("New York");
INSERT INTO states(state_name) VALUES ("North Carolina");
INSERT INTO states(state_name) VALUES ("North Dakota");
INSERT INTO states(state_name) VALUES ("Ohio");
INSERT INTO states(state_name) VALUES ("Oklahoma");
INSERT INTO states(state_name) VALUES ("Oregon");
INSERT INTO states(state_name) VALUES ("Pennsylvania");
INSERT INTO states(state_name) VALUES ("Rhode Island");
INSERT INTO states(state_name) VALUES ("South Carolina");
INSERT INTO states(state_name) VALUES ("South Dakota");
INSERT INTO states(state_name) VALUES ("Tennessee");
INSERT INTO states(state_name) VALUES ("Texas");
INSERT INTO states(state_name) VALUES ("Utah");
INSERT INTO states(state_name) VALUES ("Vermont");
INSERT INTO states(state_name) VALUES ("Virginia");
INSERT INTO states(state_name) VALUES ("Washington");
INSERT INTO states(state_name) VALUES ("West Virginia");
INSERT INTO states(state_name) VALUES ("Wisconsin");
INSERT INTO states(state_name) VALUES ("Wyoming");
